### ISSUE TITLE
Handle custom groups from all namespaces.

### ISSUE THREAD

**Issue by hemani19** [vmware/purser#188]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
If the custom group is created in any namespace other than the `default` the groups data is not populated. 

**What you expected to happen**:
Custom groups created in any namespace should be captured.

**Comment by kreddyj** [comment]
This is not relevant now, as the user creates the custom group from UI we ensure that it will be always in `default` namespace.
