### ISSUE TITLE
Cost Calculation for Storage used is incorrect

### ISSUE THREAD

**Issue by tangoe2eautomation** [vmware/purser#195]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**: Currently purser is showing that for LINT group we are using 5933(5TB) of storage. But the cost says 13.03$ which is very less. 

Cost for 1GB is 0.10$ per GB
https://aws.amazon.com/ebs/pricing/

**What you expected to happen**:
Show the correct cost for Storage usage. 

**How to reproduce it (as minimally and precisely as possible)**:
<img width="1668" alt="screen shot 2019-03-01 at 8 02 58 am" src="https://user-images.githubusercontent.com/33338338/53650040-71e0d900-3bf8-11e9-8c0e-4ce14826e4c9.png">

**Comment by kreddyj** [comment]
At present Purser provides Month to date costs i.e., cost of an application in the current month. The data shown in your screenshot was for the current month(Mar '19) and hence the cost for now in purser is calculated from March 1st. In the upcoming features we will try to provide cost viewing options for user.
