### ISSUE TITLE
Ability to see Historicial Cost Data

### ISSUE THREAD

**Issue by tangoe2eautomation** [vmware/purser#207]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
We would like to Historical Cost data. This will be helpful in doing a cost Comparison to see the cost of each Services.

**Comment by hemani19** [comment]
Let's have a UI support 3 options for the moment. 
 - This Month
 - Previous Month
 - Last 3 Months
