### ISSUE TITLE
New Group Creation doesn't give me confirm if it was created

### ISSUE THREAD

**Issue by tangoe2eautomation** [vmware/purser#213]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
kind bug
> /kind feature

**What happened**:
I was testing a new group creation feature from the UI. After entering my json file and click on create I don't see anything happen. 

**What you expected to happen**:
I would expect validation of the json and confirmation that group creation was successful

apiVersion: vmware.purser.com/v1
kind: Group
metadata:
  name: Common Log Saas
spec:
  name: Common Log Saas
  labels:
    expr1:
      app:
        - alerts-service
        - notification-service

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- golang version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kreddyj** [comment]
@tangoe2eautomation  Right now we support Group creation in JSON format only. We have updated our code to alert the user in case of incorrect format. For group creation template refer this: https://github.com/vmware/purser/blob/master/cluster/artifacts/group-template.json
