### ISSUE TITLE
Purser logo creation

### ISSUE THREAD

**Issue by rachil-chandran** [vmware/purser#23]
Create a logo for Purser and follow up with approval process.

**Comment by hemani19** [comment]
Below are the large and small designs for the approved Purser logo.
![173704-vmw-os-lgo-purser-final-lrg](https://user-images.githubusercontent.com/42761785/53145167-2cebef80-35c5-11e9-8b48-bd0d94be2239.png)
![173704-vmw-os-lgo-purser-final-sml](https://user-images.githubusercontent.com/42761785/53145168-2f4e4980-35c5-11e9-867b-8d637671ec23.png)
