### ISSUE TITLE
Helm Chart and Login credentials

### ISSUE THREAD

**Issue by Anish-Gupta-Bose** [vmware/purser#231]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

1. Deployment needs to be streamlined, this can be done easily with the help of Helm chart. If possible, can you make a helm chart for Purser.

2. Provide default login credentials and a way to disable login.

logs -

```
purser-68c74b9d9b-njwjj purser-controller ERRO[5572] rpc error: code = Unknown desc = : Attribute username is not indexed.
purser-68c74b9d9b-njwjj purser-controller ERRO[5572] rpc error: code = Unknown desc = : Attribute username is not indexed.
purser-68c74b9d9b-njwjj purser-controller INFO[5572] POST	/auth/login	Login	3.124595ms
```

**What you expected to happen**:

Default login credentials  don't work
* username - `admin`
* password - `purser!123`

found the above credentials in [search](https://github.com/vmware/purser/search?q=username&unscoped_q=username).

**How to reproduce it (as minimally and precisely as possible)**:

1. Follow the instructions in the README to deploy Purser
2. Try to login

**Anything else we need to know?**:

**Environment**:
- golang version:
- Kubernetes version (use `kubectl version`): 1.13.5
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Custom
- Kernel (e.g. `uname -a`): 5.0
- Install tools:
- Others:

**Comment by kreddyj** [comment]
Thanks for opening an Issue. While we will look into making a helm chart for Purser, we have created a commit that fixes the login issue and updated the images. Can you please restart the pods for `purser-controller` and `purser-ui`. 

**Restarting Purser UI and controller:**
_Delete and create Purser UI_
`kubectl --namespace=purser delete -f purser-ui-setup.yaml`
`kubectl --namespace=purser create -f purser-ui-setup.yaml`

_Delete and create Purser Controller_
`kubectl --namespace=purser delete -f purser-controller-setup.yaml`
`kubectl --namespace=purser create-f purser-controller-setup.yaml`

The default credentials are the same which you have mentioned in the issue. We created a new issue that should document the default login details in the installation steps. Once you restart by following the above steps, please try to login (`username - admin, password - purser!123`) and let us know if you find bugs or face any trouble with Purser.

**Comment by Anish-Gupta-Bose** [comment]
Thank you for getting back! I did what you said and now I am getting the following error - 

```
ERRO[0226] rpc error: code = Unknown desc = : Attribute name is not indexed.
2019/04/16 21:34:00 http: panic serving 100.64.11.225:34696: runtime error: index out of range
goroutine 310 [running]:
net/http.(*conn).serve.func1(0xc0007620a0)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x1140920, 0x1e43330)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/vmware/purser/pkg/controller/dgraph/models/query.getLoginCredentials(0xc000459518, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/vmware/purser/pkg/controller/dgraph/models/query/login.go:82 +0x1d5
github.com/vmware/purser/pkg/controller/dgraph/models/query.Authenticate(0xc000459518, 0x5, 0xc000459750, 0xa, 0x0)
	/go/src/github.com/vmware/purser/pkg/controller/dgraph/models/query/login.go:32 +0xa4
github.com/vmware/purser/cmd/controller/api/apiHandlers.LoginUser(0x1415ce0, 0xc0007961c0, 0xc000146400)
	/go/src/github.com/vmware/purser/cmd/controller/api/apiHandlers/authenticationHandlers.go:56 +0x12f
net/http.HandlerFunc.ServeHTTP(0x13233c0, 0x1415ce0, 0xc0007961c0, 0xc000146400)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/vmware/purser/cmd/controller/api.Logger.func1(0x1415ce0, 0xc0007961c0, 0xc000146400)
	/go/src/github.com/vmware/purser/cmd/controller/api/logger.go:31 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc0004209c0, 0x1415ce0, 0xc0007961c0, 0xc000146400)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/vmware/purser/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000038620, 0x1415ce0, 0xc0007961c0, 0xc000146400)
	/go/src/github.com/vmware/purser/vendor/github.com/gorilla/mux/mux.go:162 +0xf1
github.com/vmware/purser/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc00017da70, 0x1415ce0, 0xc0007961c0, 0xc000146000)
	/go/src/github.com/vmware/purser/vendor/github.com/gorilla/handlers/cors.go:135 +0x1f6
net/http.serverHandler.ServeHTTP(0xc000183380, 0x1415ce0, 0xc0007961c0, 0xc000146000)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0007620a0, 0x1416a20, 0xc0003d8500)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

**Comment by kreddyj** [comment]
It looks like DB connection failure, let's make a fresh clean installation.

**Uninstall:**
```
kubectl --namespace=purser delete -f purser-database-setup.yaml
kubectl --namespace=purser delete -f purser-controller-setup.yaml
kubectl --namespace=purser delete -f purser-ui-setup.yaml
kubectl --namespace=purser delete pvc datadir-purser-dgraph-0
```

**Install:**
`kubectl --namespace=purser create -f purser-database-setup.yaml`
Wait for the DB pod(purser-dgraph-0) to be in running state (check using: `kubectl -n purser get pods`)

`kubectl --namespace=purser create -f purser-controller-setup.yaml`
`kubectl --namespace=purser create -f purser-ui-setup.yaml`
Check the status of Purser pods: `kubectl -n purser get pods` and wait until all of them are in running state.

Please try to login after re-installing and let us know the result.
Thanks.

**Comment by kreddyj** [comment]
wrongly closed.

**Comment by hemani19** [comment]
Hi @Anish-Gupta-Bose 
Hope the login works for you now. 
Also, would you like to contribute to the Helm charts piece?  Would love a PR from you.

**Comment by Anish-Gupta-Bose** [comment]
@hemani19 & @kreddyj tell me if I am wrong, so the trick is to deploy the database and **wait a minute or two** before deploying the controller and the UI. The deployment works well, but I would prefer if the **authentication was optional**, if it could be disabled with an environment flag or something. Also, I had replace the nginx configuration with a ConfigMap since I am not using MiniShift or OpenShift. The product looks really good, thank you for open-sourcing this.

@hemani19 I wouldn't mind contributing the helm chart. I would revert with a PR when I can. Though, if you guys could make the authentication optional, it would be great.

**Comment by hemani19** [comment]
@Anish-Gupta-Bose, glad you liked it. UI is independent but the controller needs the database, so yes we recommend deploying the database first and then the controller and the UI to avoid running into issues.

We'll work on having the authentication feature optional, thanks for the feedback. 

Looking forward to your PR. Also, feel free to open issues and PRs if possible for alternative solutions if you think might be useful or make the project more user-friendly in terms of use and installation. (for instance, proposal to replace nginx configuration with ConfigMap if that makes it better).

**Comment by Anish-Gupta-Bose** [comment]
@hemani19 upstreaming the Helm chart in #235

**Comment by hemani19** [comment]
Thanks for your contribution @Anish-Gupta-Bose!  👍
