### ISSUE TITLE
Handle syncing of inventory when new group is created.

### ISSUE THREAD

**Issue by gurusreekanthc** [vmware/purser#34]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature

**What happened**:
Newly created group doesn't have inventory populated until new sync.

**What you expected to happen**:
Whenever new group is created sync the inventory related to that group.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new group

**Comment by kreddyj** [comment]
@hemani19 this issue is addressed in #91 right?

**Comment by kreddyj** [comment]
Closing this as our approach to update groups have changed. Refer #124
