### ISSUE TITLE
Incomplete steps for dev setup of purser

### ISSUE THREAD

**Issue by agarwalakash06** [vmware/purser#35]
DOCUMENTATION

**What happened**: Getting the following error while executing the make command 
/bin/sh: 1: gometalinter: not found
Makefile:231: recipe for target 'tools' failed
make: * [tools] Error 127

**What you expected to happen**: Error should not have come

**How to reproduce it (as minimally and precisely as possible)**: Setting up the code after installing go for the first time

**Anything else we need to know?**:  Setting the $GOPATH/bin in the path variable resolved the issue
Clone and Set Upstream Remote also has a typo in the first command
It should be cd $GOPATH/src/github.com/vmware

**Environment**:
- golang version: 1.11
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kreddyj** [comment]
@agarwalakash06 thanks for the issue. It would help us if you send pull request which fixes this issue.

**Comment by agarwalakash06** [comment]
@kreddyj Sent a pull request
