### ISSUE TITLE
Unit tests for utils

### ISSUE THREAD

**Issue by kreddyj** [vmware/purser#36]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**: 
No unit tests for `utils` folder

**What you expected to happen**:
unit tests for all functions in the `utils` folder

**Anything else we need to know?**:
`utils` folder is [here](https://github.com/vmware/purser/tree/master/pkg/controller/utils).
You can create test files in the same folder in the same folder.
Comment in this issue if you want any help.

This issue is a part of issue #16.

You can use [this test case](https://github.com/vmware/purser/blob/master/pkg/controller/dgraph/models/query/label_test.go) as a reference.

**Update**:
Files changed due to refactoring, unit tests required for most of the functions in following files:
- [unitConversion.go](https://github.com/vmware/purser/blob/master/pkg/controller/utils/unitConversions.go)
- [timeUtils.go](https://github.com/vmware/purser/blob/master/pkg/controller/utils/timeUtils.go)
- `hexToIP` function in [purge.go](https://github.com/vmware/purser/blob/master/pkg/controller/utils/purge.go#L79)

**Comment by shubhodeep9** [comment]
Hi @kreddyj 
I can contribute.
Let me know if there is still a need.

**Comment by kreddyj** [comment]
@shubhodeep9 thanks for the interest. You can work on it.

**Comment by shubhodeep9** [comment]
Hi @kreddyj 
I am finding it difficult to understand the logic, without comments, 
can you please help me understand `currentMonthActiveTimeInHours` and `currentMonthActiveTimeInHoursMulti`, what are their purpose?

**Comment by kreddyj** [comment]
@shubhodeep9 These functions aim is to find number of hours from `startTime` to `endTime`.
`currentMonthActiveTimeInHours` takes two arguments `startTime` and `endTime`.
It will evaluate `currentTime` i,e, present time and also `monthStart` i,e, time of 1st second of the current month(Example: 1st October 2018, 00hrs:00mins:01sec). Then it will pass `startTime`, `endTime`, `currentTime` and `monthStart` as  arguments to `currentMonthActiveTimeInHoursMulti`.

In `currentMonthActiveTimeInHoursMulti`, it checks whether the `startTime` is before `monthStart`. If it is before `monthStart` then `startTime` is set as `monthStart`. The function also checks whether `endTime` is initialized or not. If it is not initialized then `endTime.IsZero()` will give `true` and if it is so then `endTime` is set as `currentTime`. Now as both `startTime` and `endTime` are set the function `currentMonthActiveTimeInHoursMulti` will find number of hours from `startTime` to `endTime`.

**Comment by shubhodeep9** [comment]
ok, thanks
@kreddyj
