### ISSUE TITLE
Add support for user preferences.

### ISSUE THREAD

**Issue by hemani19** [vmware/purser#51]
Currently, everything is enabled by `default` and no customizations are supported. We should have a mechanism by which the user can provide/set their preferences such as the features they want to enable, the level of logging they want, the option to select a particular namespace etc.

One of the ways to achieve this could be through the use of a config file. 

@gurusreekanthc @kreddyj we should propose some suggestions on this.

- [x] Option for log level
- [x] Option for enabling/disabling discovery of inventory features
- [x] Option for dgraph zero url and port

**Comment by kreddyj** [comment]
The controller will be deployed as a container, I am not sure whether customization through a config file is feasible or not.
