### ISSUE TITLE
Code clean up tasks

### ISSUE THREAD

**Issue by hemani19** [vmware/purser#7]
To improve the contributor experience and have the code clean, the following listed tasks should be fixed.

- [x] Remove `/vendor` directory from being committed to GitHub as per this [explanation](https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md).

- [ ] Add an `install` target to install the external dependencies in the Makefile and update `README.md` with the new information regarding the same. 

- [x] Replace existing targets with [`Phony targets`](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) in the Makefile.

- [ ] Add a dedicated directory to store all the generated files like `docker-images` and `container-files` and include this directory in `.gitignore` to prevent it from being accidentally committed.

**Comment by kreddyj** [comment]
Also edit `.travis.yml` to download dependencies before it builds. Just add `make install` before `make travis-build` in the script section.
